import = ["~/.config/alacritty/themes/one_dark.toml"]

[env]
TERM = "alacritty-direct"
HELLO = "world"

[font]
size = 8.5

[font.normal]
family = "Geist Mono"

[font.offset]
y = 14

[window]
startup_mode = "Fullscreen"

[window.padding]
x = 8
y = 8
