
[env]
TERM = "alacritty-direct"

[window]
opacity = 0.98


[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
offset = { x = 0, y = 8 }
size = 11

[general]
import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

