
require('core.plugin_config.catpuccin')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.gitsigns')
require('core.plugin_config.coc')
require('core.plugin_config.todo-comments')
require('core.plugin_config.prettier')
